config/routes.rb
Rails.application.routes.draw do
  resources :resolutions
  resources :parametros
  get 'saldos/recagas'
  get 'saldos/movimientos'
  
  get 'saldos/recagas'
  get 'saldos/movimientos'
  resources :enunciados do
  resources :resolutions
  end
  resources :priorities
  resources :courses
  resources :movimiento_saldo, only: [:index]
root to:  'pages#home'
get "enunciados/:id" => "enunciados#show2"
get "resolutions" => "resolutions#listar"
resources :resolutions
get 'listar'  , to: "resolutions#listar"
get 'showReso/:id', to: "enunciados#showReso"
get 'showReso2/:id', to: "resolutions#showReso2"
get 'ListaReso', to: "enunciados#ListaReso"
  devise_for :users#, controllers: { registrations: "registrations"}
  #as :user do
   # get '/' => 'devise/registrations#new'
  #end 
    
  resources :pages
 get 'profile_teacher', to: "pages#profile_teacher"
 get 'profile_student', to: "pages#profile_student"
  get 'profile_administrator', to: "pages#profile_administrator"
 get 'edit_profile', to: "pages#edit_profile"

 get '*path'=> redirect('/')
 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/parametro.rb
class Parametro < ApplicationRecord
    has_one :enunciados
    has_one :resolutions
end

app/controllers/parametros_controller.rb
class ParametrosController < ApplicationController
  before_action :set_parametro, only: [:show, :edit, :update, :destroy]

  # GET /parametros
  # GET /parametros.json
  def index
    @parametros = Parametro.all
  end

  # GET /parametros/1
  # GET /parametros/1.json
  def show
  end

  # GET /parametros/new
  def new
    @parametro = Parametro.new
  end

  # GET /parametros/1/edit
  def edit
  end

  # POST /parametros
  # POST /parametros.json
  def create
    @parametro = Parametro.new(parametro_params)

    respond_to do |format|
      if @parametro.save
        format.html { redirect_to @parametro, notice: 'Parametro was successfully created.' }
        format.json { render :show, status: :created, location: @parametro }
      else
        format.html { render :new }
        format.json { render json: @parametro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parametros/1
  # PATCH/PUT /parametros/1.json
  def update
    respond_to do |format|
      if @parametro.update(parametro_params)
        format.html { redirect_to @parametro, notice: 'Parametro was successfully updated.' }
        format.json { render :show, status: :ok, location: @parametro }
      else
        format.html { render :edit }
        format.json { render json: @parametro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parametros/1
  # DELETE /parametros/1.json
  def destroy
    @parametro.destroy
    respond_to do |format|
      format.html { redirect_to parametros_url, notice: 'Parametro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_parametro
      @parametro = Parametro.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def parametro_params
      params.require(:parametro).permit(:grupo, :codigo, :description, :estado)
    end
end

app/helpers/parametros_helper.rb
module ParametrosHelper
end

app/views/parametros/_form.html.erb
<%= form_with(model: parametro, local: true) do |form| %>
  <% if parametro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(parametro.errors.count, "error") %> prohibited this parametro from being saved:</h2>

      <ul>
        <% parametro.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :grupo %>
    <%= form.number_field :grupo %>
  </div>

  <div class="field">
    <%= form.label :codigo %>
    <%= form.number_field :codigo %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :estado %>
    <%= form.number_field :estado %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/parametros/edit.html.erb
<h1>Editing Parametro</h1>

<%= render 'form', parametro: @parametro %>

<%= link_to 'Show', @parametro %> |
<%= link_to 'Back', parametros_path %>

app/views/parametros/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Parametros</h1>

<table>
  <thead>
    <tr>
      <th>Grupo</th>
      <th>Codigo</th>
      <th>Description</th>
      <th>Estado</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @parametros.each do |parametro| %>
      <tr>
        <td><%= parametro.grupo %></td>
        <td><%= parametro.codigo %></td>
        <td><%= parametro.description %></td>
        <td><%= parametro.estado %></td>
        <td><%= link_to 'Show', parametro %></td>
        <td><%= link_to 'Edit', edit_parametro_path(parametro) %></td>
        <td><%= link_to 'Destroy', parametro, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Parametro', new_parametro_path %>

app/views/parametros/new.html.erb
<h1>New Parametro</h1>

<%= render 'form', parametro: @parametro %>

<%= link_to 'Back', parametros_path %>

app/views/parametros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Grupo:</strong>
  <%= @parametro.grupo %>
</p>

<p>
  <strong>Codigo:</strong>
  <%= @parametro.codigo %>
</p>

<p>
  <strong>Description:</strong>
  <%= @parametro.description %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @parametro.estado %>
</p>

<%= link_to 'Edit', edit_parametro_path(@parametro) %> |
<%= link_to 'Back', parametros_path %>