config/routes.rb
Rails.application.routes.draw do
  resources :resolutions
  resources :parametros
  get 'saldos/recagas'
  get 'saldos/movimientos'
  
  get 'saldos/recagas'
  get 'saldos/movimientos'
  resources :enunciados do
  resources :resolutions
  end
  resources :priorities
  resources :courses
  resources :movimiento_saldo, only: [:index]
root to:  'pages#home'
get "enunciados/:id" => "enunciados#show2"
get "resolutions" => "resolutions#listar"
resources :resolutions
get 'listar'  , to: "resolutions#listar"
get 'showReso/:id', to: "enunciados#showReso"
get 'showReso2/:id', to: "resolutions#showReso2"
get 'ListaReso', to: "enunciados#ListaReso"
  devise_for :users#, controllers: { registrations: "registrations"}
  #as :user do
   # get '/' => 'devise/registrations#new'
  #end 
    
  resources :pages
 get 'profile_teacher', to: "pages#profile_teacher"
 get 'profile_student', to: "pages#profile_student"
  get 'profile_administrator', to: "pages#profile_administrator"
 get 'edit_profile', to: "pages#edit_profile"

 get '*path'=> redirect('/')
 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/priority.rb
class Priority < ApplicationRecord
    validates :description,:costo  ,   :descosto, presence:{message: "Obligatorio"}

    belongs_to :enunciados
   
    before_save :default_values 
  def default_values 
    self.idestado ||= 1
   end

end

app/controllers/priorities_controller.rb
class PrioritiesController < ApplicationController
  before_action :set_priority, only: [:show, :edit, :update, :destroy]

  # GET /priorities
  # GET /priorities.json
  def index
    @priorities = Priority.all
  end

  # GET /priorities/1
  # GET /priorities/1.json
  def show
  end

  # GET /priorities/new
  def new
    @priority = Priority.new
  end

  # GET /priorities/1/edit
  def edit
  end

  # POST /priorities
  # POST /priorities.json
  def create
    @priority = Priority.new(priority_params)

    respond_to do |format|
      if @priority.save
        format.html { redirect_to @priority, notice: 'Priority was successfully created.' }
        format.json { render :show, status: :created, location: @priority }
      else
        format.html { render :new }
        format.json { render json: @priority.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /priorities/1
  # PATCH/PUT /priorities/1.json
  def update
    respond_to do |format|
      if @priority.update(priority_params)
        format.html { redirect_to @priority, notice: 'Priority was successfully updated.' }
        format.json { render :show, status: :ok, location: @priority }
      else
        format.html { render :edit }
        format.json { render json: @priority.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /priorities/1
  # DELETE /priorities/1.json
  def destroy
    @priority.destroy
    respond_to do |format|
      format.html { redirect_to priorities_url, notice: 'Priority was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_priority
      @priority = Priority.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def priority_params
      params.require(:priority).permit(:description, :costo, :descosto, :idestado)
    end
end

app/helpers/priorities_helper.rb
module PrioritiesHelper
end

app/views/priorities/_form.html.erb
<%= form_with(model: priority, local: true) do |form| %>
  <% if priority.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(priority.errors.count, "error") %> prohibited this priority from being saved:</h2>

      <ul>
        <% priority.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :costo %>
    <%= form.text_field :costo %>
  </div>

  <div class="field">
    <%= form.label :descosto %>
    <%= form.text_area :descosto %>
  </div>

  <div class="field">
    <%= form.label :idestado %>
    <%= form.number_field :idestado %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/priorities/edit.html.erb
<h1>Editing Priority</h1>

<%= render 'form', priority: @priority %>

<%= link_to 'Show', @priority %> |
<%= link_to 'Back', priorities_path %>

app/views/priorities/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>

<%= render 'layouts/menu'  %>
<div class= "contrainer" style = "margin-left:380px; margin-top:50px;"> 
<p id="notice"><%= notice %></p>

<h1>Priorities</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Costo</th>
      <th>Descosto</th>
      <th>Idestado</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @priorities.each do |priority| %>
      <tr>
        <td><%= priority.description %></td>
        <td><%= priority.costo %></td>
        <td><%= priority.descosto %></td>
        <td><%= priority.idestado %></td>
        <td><%= link_to 'Show', priority %></td>
        <td><%= link_to 'Edit', edit_priority_path(priority) %></td>
        <td><%= link_to 'Destroy', priority, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Priority', new_priority_path %>
</div>
    </body>
</html>

app/views/priorities/new.html.erb
<h1>New Priority</h1>

<%= render 'form', priority: @priority %>

<%= link_to 'Back', priorities_path %>

app/views/priorities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @priority.description %>
</p>

<p>
  <strong>Costo:</strong>
  <%= @priority.costo %>
</p>

<p>
  <strong>Descosto:</strong>
  <%= @priority.descosto %>
</p>

<p>
  <strong>Idestado:</strong>
  <%= @priority.idestado %>
</p>

<%= link_to 'Edit', edit_priority_path(@priority) %> |
<%= link_to 'Back', priorities_path %>