config/routes.rb
Rails.application.routes.draw do
  resources :resolutions
  resources :parametros
  get 'saldos/recagas'
  get 'saldos/movimientos'
  
  get 'saldos/recagas'
  get 'saldos/movimientos'
  resources :enunciados do
  resources :resolutions
  end
  resources :priorities
  resources :courses
  resources :movimiento_saldo, only: [:index]
root to:  'pages#home'
get "enunciados/:id" => "enunciados#show2"
get "resolutions" => "resolutions#listar"
resources :resolutions
get 'listar'  , to: "resolutions#listar"
get 'showReso/:id', to: "enunciados#showReso"
get 'showReso2/:id', to: "resolutions#showReso2"
get 'ListaReso', to: "enunciados#ListaReso"
  devise_for :users#, controllers: { registrations: "registrations"}
  #as :user do
   # get '/' => 'devise/registrations#new'
  #end 
    
  resources :pages
 get 'profile_teacher', to: "pages#profile_teacher"
 get 'profile_student', to: "pages#profile_student"
  get 'profile_administrator', to: "pages#profile_administrator"
 get 'edit_profile', to: "pages#edit_profile"

 get '*path'=> redirect('/')
 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/pages/cancel_acount.html.erb
<h3>Cancel my account</h3>

<p>Unhappy? <%= button_to "Cancel my account", registration_path(resource_name), data: { confirm: "Are you sure?" }, method: :delete %></p>

<%= link_to "Back", :back %>

app/views/pages/edit_profile.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body >
<h1>Editar datos</h1>


</body>
</html>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>KongLab</title>

  <!-- Bootstrap core CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  <!-- Custom fonts for this template -->
  <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template -->
</head>
<body>
  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top text-right">
    <div class="container">
      <a class="navbar-brand " href="#">KongLab</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>


      <ul class="navbar-nav ml-auto">
      <% if  current_user %>
        <% if  current_user.tipo == "Alumno"  %>
      <li class="nav-item">
        <p class="nav-link " ><%= link_to "Mi perfil", profile_student_path, :class => "font-weight-bold  text-white text-right" %></p>
      </li>
      <% elsif current_user.tipo == "Profesor" %>
      <li class="nav-item">
        <p class="nav-link" >  <%= link_to "Mi perfil", profile_teacher_path, :class => "font-weight-bold  text-white text-right"%></p>
      </li>
      <% else %>    
      <li class="nav-item">   <p class="nav-link" >      
      <%= link_to "Mi perfil", profile_administrator_path, :class => "font-weight-bold  text-white text-right" %>
     <% end %></p>
     </li>
     <li class="nav-item">  
      <p class="nav-link" > <%= link_to "Salir sesion", destroy_user_session_path, method: :delete, :class => "font-weight-bold  text-white" %>
      </p>
     </li>

    </ul>
        <% else %>
     <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <p class="nav-link " ><%= link_to 'Registrarse' , new_user_registration_path,  :class => "font-weight-bold  text-white" %></p>
          </li>
          <li class="nav-item">

            <p class="nav-link" > <%= link_to 'Iniciar Sesion', new_user_session_path , :class => "font-weight-bold  text-white" %></p>
          </li>
        </ul>
      </div>
      <% end %>
    </div>
  </nav>

  <header class="masthead text-center text-white">
    <div class="masthead-content">
      <div class="container">
        <h1 class="masthead-heading mb-0">Conocimiento para todos </h1>
        <h2 class="masthead-subheading mb-0">al alcance de un click</h2>
        <a href="#" class="">
          <% if current_user %>     
        <%= link_to "Publicar consulta", new_enunciado_path, :class => "btn btn-primary btn-xl rounded-pill mt-5 font-weight-bold lead text-white"  %></a>
            <% else %>
            <%= link_to "Publicar consulta", new_user_session_path, :class => "btn btn-primary btn-xl rounded-pill mt-5 font-weight-bold lead text-white"  %></a>
        <% end %>
        </div>
    </div>
    <div class="bg-circle-1 bg-circle"></div>
    <div class="bg-circle-2 bg-circle"></div>
    <div class="bg-circle-3 bg-circle"></div>
    <div class="bg-circle-4 bg-circle"></div>
  </header>

  <!-- Footer -->
  <footer class="py-5 bg-black">
    <div class="container">
      <p class="m-0 text-center text-white small">Copyright &copy; Derechos reservados  2020</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
  

</body>

app/views/pages/profile_administrator.html.erb
<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<title></title>

	<link href="https://fonts.googleapis.com/css?family=Lato:400,700&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">	
	<style type="0"></style>
</head>
<body>
	<nav class="navbar navbar-dark navbar-custom fixed-top " style=" margin-left: 349px;">
    <div class="container" >
      <a class="navbar-brand" href="/portada/index" >Bienvenido a tu perfil Administrador</a>
        
      </div>
    
  </nav>


	<section class="lateral shadow-lg bg-dark">
		<div class="row justify-content-center pt-4">
			<img src="#" alt="" class="rounded-pill perfil_circulo">
		</div >
		<div class="row justify-content-center pt-4">
			<h1 class="perfil_nombres"><%= current_user.name  %> <%= current_user.apellido%></h1>
		</div>
	<div class="menulist" >
	  <ul class="list-group " >
	    <li class="list-group-item"> <a href="/enunciados">Historial de solicitudes</a></li>
	    <li class="list-group-item"><a href=""><%= link_to "Solicitar cambio de perfil", edit_user_registration_path  %></a></li>
	    <li class="list-group-item"><a href=""><%= link_to "Solicitar Resolucion de ejercicio", new_enunciado_path  %></a></li>
	    <li class="list-group-item"><a href="/movimiento_saldo">Saldos y movimientos</a></li>  
	    <li class="list-group-item"> <a href="/courses">Mantenimiento de Cursos</a></li>
	    <li class="list-group-item"> <a href="/priorities">Mantenimiento de Prioridades</a></li>
	    <li class="list-group-item"><a href="http://localhost:3000/"></a><%= link_to "Menu principal", root_path, method: :delete %></li>
	    <li class="list-group-item"><a href=""><%= link_to "Salir sesion", destroy_user_session_path, method: :delete %></a></li>
	  </ul>
	</div>
		
	</section>

	<section class="proyectos">
		
	</section>


	
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>	
</body>
</html>

app/views/pages/profile_student.html.erb
<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<title></title>



	<link href="https://fonts.googleapis.com/css?family=Lato:400,700&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">	
</head>
<body>
	<nav class="navbar navbar-dark navbar-custom fixed-top " style=" margin-left: 349px;">
    <div class="container" >
    

      <a class="navbar-brand" href="" >Bienvenido a tu perfil Alumno</a>


	<section class="lateral shadow-lg bg-dark">
		
		<div class="row justify-content-center pt-4">
			<img src="#" alt="" class="rounded-pill perfil_circulo">
		</div >
		<div class="row justify-content-center pt-4">
			<h1 class="perfil_nombres"><%= current_user.name  %> <%= current_user.apellido%></h1>
		</div>
	<nav>
	<div class="menulist">
			<ul class="list-group ">
            <li class="list-group-item"><a href=""><%= link_to "Solicitar Resolucion de ejercicio", new_enunciado_path  %></a></li>
			<li class="list-group-item"> <a href="/enunciados">Historial de solicitudes</a></li>
      		<li class="list-group-item"> <a href="/ListaReso">Ejercicios Resueltos</a></li>
					  
			<a class="list-group-item" href="/movimiento_saldo">Saldos y movimientos</a>  
			<li class="list-group-item"><a href="/profile_student">menu principal</a></li>		
			<li class="list-group-item"><a href=""><%= link_to "Salir sesion", destroy_user_session_path, method: :delete %></a></li>
			</ul>
		</div>
</section>
		
	</section>

	<section class="proyectos">
		
	</section>
Z

	
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>	
</body>
</html>

app/views/pages/profile_teacher.html.erb
<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<title></title>

	<link href="https://fonts.googleapis.com/css?family=Lato:400,700&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">	
</head>
<body>
	<nav class="navbar navbar-dark navbar-custom fixed-top " style=" margin-left: 349px;">
    <div class="container" >
      <a class="navbar-brand" href="/portada/index" >Bienvenido a tu perfil Profesor</a>
        
      </div>
    
  </nav>


	<section class="lateral shadow-lg bg-dark">
		
		<div class="row justify-content-center pt-4">
			<img src="#" alt="" class="rounded-pill perfil_circulo">
		</div >
		<div class="row justify-content-center pt-4">
			<h1 class="perfil_nombres"><%= current_user.name  %> <%= current_user.apellido%></h1>
		</div>
	
		<div class="menulist">
			<ul class="list-group ">
			  <li class="list-group-item"> <a href="/resolutions">Lista de solicitudes Pendientes</a></li>
			  <li class="list-group-item"> <a href="/listar">Historial de solicitudes resueltos</a></li>
              <li class="list-group-item"><a href=""><%= link_to "Solicitar cambio de perfil", edit_user_registration_path  %></a></a></li>
              <li class="list-group-item"><a href=""><%= link_to "Editar Datos", edit_profile_path  %></a></li>			  
			  <a class="list-group-item" href="/movimiento_saldo">Saldos y movimientos</a>  
			  <li class="list-group-item"><a href="/profile_teacher"><%= link_to "Menu principal" %></a></li>
			  <li class="list-group-item"><a href=""><%= link_to "Salir sesion", destroy_user_session_path, method: :delete %></a></li>
			</ul>
		</div>
		
	</section>

	<section class="proyectos">
		
	</section>


	
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>	
</body>
</html>