config/routes.rb
Rails.application.routes.draw do
  resources :resolutions
  resources :parametros
  get 'saldos/recagas'
  get 'saldos/movimientos'
  
  get 'saldos/recagas'
  get 'saldos/movimientos'
  resources :enunciados do
  resources :resolutions
  end
  resources :priorities
  resources :courses
  resources :movimiento_saldo, only: [:index]
root to:  'pages#home'
get "enunciados/:id" => "enunciados#show2"
get "resolutions" => "resolutions#listar"
resources :resolutions
get 'listar'  , to: "resolutions#listar"
get 'showReso/:id', to: "enunciados#showReso"
get 'showReso2/:id', to: "resolutions#showReso2"
get 'ListaReso', to: "enunciados#ListaReso"
  devise_for :users#, controllers: { registrations: "registrations"}
  #as :user do
   # get '/' => 'devise/registrations#new'
  #end 
    
  resources :pages
 get 'profile_teacher', to: "pages#profile_teacher"
 get 'profile_student', to: "pages#profile_student"
  get 'profile_administrator', to: "pages#profile_administrator"
 get 'edit_profile', to: "pages#edit_profile"

 get '*path'=> redirect('/')
 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/enunciado.rb
class Enunciado < ApplicationRecord
  validates :tema , :description ,:avatar,     presence:{message: "Obligatorio"}
  
  belongs_to :course
  belongs_to :priority
  belongs_to :user
  belongs_to :parametro
  has_one_attached :avatar
  has_many :resolutions

  #before_save :default_values 
  #def default_values 
    #self.estado ||= 1
   #end

   before_save :default_values 
   def default_values 
   self.estado ||= 1
   
   end
  
end

app/controllers/enunciados_controller.rb
class EnunciadosController < ApplicationController
  before_action :set_enunciado, only: [:show, :edit, :update, :destroy ]


  # GET /enunciados
  # GET /enunciados.json
  def index
    @enunciados = Enunciado.where(estado: 1, user_id:current_user).order(created_at: :desc)
  end


  # GET /enunciados/1
  # GET /enunciados/1.json
  def show
    @enunciado = Enunciado.find(params[:id])
  end

  def showReso
    @enunciado = Enunciado.find(params[:id])
  end


  def ListaReso
    @enunciados = Enunciado.where(estado: 1, user_id:current_user).order(created_at: :desc)
    @resolutions =Resolution.where(estado: 1, parametro_id:6 ).order(created_at: :desc)

  
  end
  def listar
    #@resolutions = Resolution.all
    @resolutions =  Resolution.where(estado: 1, user_id:current_user).order(created_at: :desc)
    
  end











  # GET /enunciados/new
  def new
    @enunciado = Enunciado.new
  end

  # GET /enunciados/1/edit

  def edit
    @enunciado = Enunciado.find(params[:id])
  end
  
  
  # POST /enunciados
  # POST /enunciados.json
  def create
    @enunciado = current_user.enunciados.new(enunciado_params)
    respond_to do |format|
      if @enunciado.save
        format.html { redirect_to @enunciado, notice: 'Enunciado fue creado correctamente' }
        format.json { render :show, status: :created, location: @enunciado }
      else
        format.html { render :new }
        format.json { render json: @enunciado.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enunciados/1
  # PATCH/PUT /enunciados/1.json
  def update
    respond_to do |format|
      if @enunciado.update(enunciado_params)
        @enunciado.estado= 0
        format.html { redirect_to @enunciado, notice: 'Enunciado fue actualizado correctamente.' }
        format.json { render :show, status: :ok, location: @enunciado }
      else
        format.html { render :edit }
        format.json { render json: @enunciado.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enunciados/1
  # DELETE /enunciados/1.json
  def destroy
    respond_to do |format|
      @enunciado.update estado: 0
  
        format.html { redirect_to enunciados_url, notice: 'Enunciado fue elimado correctamente' }
        format.json { render :enunciados, status: :ok, location: @enunciado }
    
  end
end

def destroy2
  @enunciado.destroy
  respond_to do |format|
    format.html { redirect_to enunciados_url, notice: 'Enunciado fue elimado correctamente' }
    format.json { head :no_content }
  end
end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enunciado
      @enunciado = Enunciado.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def enunciado_params
      params.require(:enunciado).permit(:tema, :description, :estado, :course_id, :priority_id, :user_id,:avatar , :parametro_id)
    end
  

end

app/helpers/enunciados_helper.rb
module EnunciadosHelper
end

app/views/enunciados/ListaReso.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>

<%= render 'layouts/menuAlumno'  %>
<div class= "contrainer" style = "margin-left:380px; margin-top:50px;"> 
<p id="notice"><%= notice %></p>
<div>
<h1 class="col-md-12 text-center"> Lista  de Solicitudes Resueltos</h1>
</div>
<div class="col-md-12 text-right">

</div>

<table class="table table-bordered" >
  <thead class="bg-info">
    <tr>
      <th>Fecha........</th>
      <th>Usuario</th>
      <th>Curso</th>
      <th>Descripción</th>
      <th>Prioridad</th>
     <th>Tema</th>
     <th>Estado</th>
      <th>Archivo</th>
      <th>Costo</th>
      

     <th>Fecha........</th>
       <th>profesor</th>
        <th>Comentario</th>
    <th>Archivo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @resolutions.each do |resolut| %>
      <tr>
      <td><%= resolut.enunciado.created_at.strftime("%d-%m-%Y") %></td>
       <td><%= resolut.enunciado.user.name%></td>
     <td><%= resolut.enunciado.course.description%></td>
     <td><%= resolut.enunciado.description %></td>
    <td><%= resolut.enunciado.priority.description %></td>
     <td><%= resolut.enunciado.tema %></td>
     <td><%= resolut.enunciado.parametro.description %></td>


<td>
<%= link_to   rails_blob_url(resolut.enunciado.avatar, disposition: 'preview') do %> 
<%= content_tag :span, "clic", :class => "btn btn-link" %>
<% end %>
</td>

         <td><%= resolut.enunciado.priority.costo %></td>
      
       <td><%= resolut.created_at.strftime("%d-%m-%Y") %></td>
        <td><%= resolut.user.name%></td>
         <td><%= resolut.comentario%></td>
       
    
<td>
<%= link_to   rails_blob_url(resolut.avatar, disposition: 'preview') do %> 
<%= content_tag :span, "clic", :class => "btn btn-link" %>
<% end %>
</td>   
       
      </tr>
    <% end %>
  </tbody>


</table>

</div>
    </body>
</html>

app/views/enunciados/_form.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>

<%= render 'layouts/menuAlumno'  %>
<div class= "contrainer" style = "margin-left:380px; margin-top:30px;"> 

      <%= form_with(model: enunciado, local: true) do |form| %>
        <% if enunciado.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(enunciado.errors.count, "error") %> prohibited this enunciado from being saved:</h2>

            <ul>
              <% enunciado.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
      
          
      <div class ="row">
        <div class ="col-6">

      <div class="container">

          <div class="form-group ">
          <%= form.label :Cursos %>
          <!--<%= form.text_field :courses_id %>-->
          <%= form.select :course_id, options_for_select(Course.all.map{|e|[e.description, e.id]}),
              {:prompt => 'Seleccione'}, {class:"form-control"}%> 
        </div>


   <div class="form-group">
    <%= form.label :Tema %>
    <%= form.text_field :tema ,class: 'form-control' %> 
  </div>
    <!--<div class="form-group ">
    <%= form.label :Prioridad %> 
    <%= form.collection_select :idprioridad, Priority.order(:description), :id, 
                                     "descosto", 
                 {:prompt => 'Seleccione' }%>

          </div>
          -->
        
      <div class="form-group ">
          <%= form.label :Prioridad %>
        <%= form.select :priority_id, options_for_select(Priority.order(:description).all.map{|e|[e.descosto, e.id]}),
              {:prompt => 'Seleccione'}, {class:"form-control"}%>
        </div>
        

  <div class="field">
<%= form.hidden_field :parametro_id, :value => "4" %>
</div>
  

  <!--<div class="form-group">
    <%= form.label :Usuario %>
    <%= form.number_field :idusuario ,class: 'form-control' %> 
  </div>-->


        <div class="form-group">
          <%= form.label :Descripción %>
          <%= form.text_area :description ,class: 'form-control' %> 
        </div>

        <div class="form-group ">
          <%= form.label :Archivo %> 
          <%= form.file_field :avatar  %> 
          </div>

      <div class="actions">
        <%= form.submit :Guardar , class: 'btn btn-primary btn-lg'%>
        </div>

        </div>
          </div>
        </div>
         <% end %>
      </div>
    </body>
</html>

app/views/enunciados/edit.html.erb
<h1  class="col-md-12 text-center">Editando Enunciado</h1>

<%= render 'form', enunciado: @enunciado %>

<%= link_to  @enunciado do  %> 
<%= content_tag :span, 'Mostrar', :type=>"button", :class => "btn btn-link" %>
<% end %>
|


<%= link_to enunciados_path do  %>
<%= content_tag :span, "Regresar", :type=>"button", :class => "btn btn-link" %>
<% end %>

app/views/enunciados/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>

<%= render 'layouts/menuAlumno'  %>
<div class= "contrainer" style = "margin-left:380px; margin-top:50px;"> 
<p id="notice"><%= notice %></p>

<h1 class="col-md-12 text-center">Lista de Solicitud de Ejercicios</h1>

<table class="table table-bordered" >
  <thead class="bg-info">
    <tr>
      <th>Fecha.........</th>
      <th>Curso</th>
      <th>Prioridad</th>
      <th>Usuario</th>
      <th>Tema</th>
      <th>Descripción</th>
      <th>Estado</th>
      <th>Archivo</th>
      <th>Costo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @enunciados.each do |enunciado| %>
      <tr>
      <td><%= enunciado.created_at.strftime("%d-%m-%Y") %></td>
     <td><%= enunciado.course.description%></td>
     <td><%= enunciado.priority.description %></td>
     <td><%= enunciado.user.name%></td>
     <td><%= enunciado.tema %></td>
     <td><%= enunciado.description %></td>
     <td><%= enunciado.parametro.description %></td>

<td>
<%= link_to   rails_blob_url(enunciado.avatar, disposition: 'preview') do %> 
<%= content_tag :span, "clic-ver", :class => "btn btn-link" %>
<% end %>
</td>

        <td><%= enunciado.priority.costo %></td>


       
           
        <td><%= link_to 'Detalle', enunciado %></td>
  
        <td><%= link_to 'Editar', edit_enunciado_path(enunciado) %></td>
        <td><%= link_to 'Eliminar', enunciado, method: :delete, data: { confirm: 'Estas Seguro de eliminar?' } %></td>
       
      </tr>
    <% end %>
  </tbody>



</table>

</div>
    </body>
</html>

app/views/enunciados/new.html.erb
<h1  class="col-md-12 text-center pt-5">Nueva Solicitud de Ejercicios</h1>

<%= render 'form', enunciado: @enunciado %>


<%= link_to enunciados_path do %>
<%= content_tag :span, "Regresar", :type=>"button", :class => "btn btn-link" %>
<% end %>

app/views/enunciados/show.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>

<%= render 'layouts/menuAlumno'  %>
<div class= "contrainer" style = "margin-left:380px; margin-top:50px;"> 

<p id="notice"><%= notice %></p>

<h1 class="col-md-12 text-center" >Detalle  de Solicitud</h1>


<div >

<table   class="table table-bordered" >
  <thead class="bg-info">
    <tr >

      <th>Fecha </th>
      <th>Curso</th>
      <th>Prioridad</th>
      <th>Usuario</th>
      <th>Tema</th>
      <th>Descripción</th>
      
      <th>Archivo</th>
      <th>Costo</th>
    </tr>
  </thead>
 <tbody>
 <tr>

  
 <td><%=  @enunciado.created_at.strftime("%d-%m-%Y") %></td>
     <td><%= @enunciado.course.description%></td>
     <td><%= @enunciado.priority.description %></td>
     <td><%= @enunciado.user.name%></td>
     <td><%= @enunciado.tema %></td>
        <td><%= @enunciado.description %></td>
 

<td>
<%= link_to   rails_blob_url(@enunciado.avatar, disposition: 'preview') do %> 
<%= content_tag :span, "Visualizar", :class => "btn btn-link" %>
<% end %>
</td>

        <td><%= @enunciado.priority.costo %></td>


 </tr>
</tbody>
  </table>
 
 

         
 


</div>
    </body>
</html>

app/views/enunciados/showReso.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>

<%= render 'layouts/menuprofesor'  %>
<div class= "contrainer" style = "margin-left:380px; margin-top:50px;"> 

<p id="notice"><%= notice %></p>

<h1 class="col-md-12 text-center" >Detalle  de Solicitud</h1>


<div >

<table   class="table table-bordered" >
  <thead class="bg-info">
    <tr >

      <th>Fecha </th>
      <th>Curso</th>
      <th>Prioridad</th>
      <th>Usuario</th>
      <th>Tema</th>
      <th>Descripción</th>
      
      <th>Archivo</th>
      <th>Costo</th>
    </tr>
  </thead>
 <tbody>
 <tr>

  
 <td><%=  @enunciado.created_at.strftime("%d-%m-%Y") %></td>
     <td><%= @enunciado.course.description%></td>
     <td><%= @enunciado.priority.description %></td>
     <td><%= @enunciado.user.name%></td>
     <td><%= @enunciado.tema %></td>
        <td><%= @enunciado.description %></td>
 

<td>
<%= link_to   rails_blob_url(@enunciado.avatar, disposition: 'preview') do %> 
<%= content_tag :span, "Visualizar", :class => "btn btn-link" %>
<% end %>
</td>

        <td><%= @enunciado.priority.costo %></td>


 </tr>
</tbody>
  </table>
 
   <!--<% if @enunciado.avatar.attached?%>
  <%=  image_tag  url_for(@enunciado.avatar)   %>
<% end %>-->


         
         
<h2>Resolución de Ejercicio:</h2>
  <%=render "resolutions/form" %>


</div>
    </body>
</html>